Rewrite ca224d81535c903e07a30bd6d5a9569f8ac2087e

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -37,27 +37,30 @@ lnsafe() {
     ln "$@" 2> /dev/null || sudo ln "$@" || logerr '----`ln '"$*"'` failed.'
 }
 
+mvsafeinternal() {
+    mv -- "$1" "$2" 2> /dev/null || sudo mv -- "$1" "$2" || logerr '----`mv -- '"$*"'` failed.'
+}
+
 mvsafe() {
-    dir="${3%/*}"
-    while true; do
-        dir="${dir%/*}"
-        [ -d "$dir" ] && {
-            dir="${3##"$dir"}"
-            dir="${dir#/}"
-            dir="${dir%/*}"
-            prevpwd="$PWD"
-            while [ -n "$dir" ]; do
-                i="${dir%%/*}"
-                mkdir -- "$i" || logerrq "Error code 1"
-                cdsafe "$i"
-                reali="${PWD#"$basedir/root"}"
-                stat --printf='%a\0%U:%G\0' -- "$reali" | xargs -0r -n 2 sh -c 'sudo chmod "$2" -- "$1"; sudo chown "$3:$4" -- "$1";' "$i" || logerrq "Error code 2"
-            done
-            break
+    newdir="${2%/*}"
+    newdir="${newdir#"$basedir/root"}"
+    basenewdir="$dir"
+    while [ ! -d "$basenewdir" ]; do
+        basenewdir="${basenewdir%/*}"
+        [ -z "$basenewdir" ] && {
+            mvsafeinternal "$@"
+            return "$?"
         }
     done
-    cdsafe "$prevpwd"
-    mv "$@" 2> /dev/null || sudo mv "$@" || logerr '----`mv -- '"$*"'` failed.'
+    mkdir -p -- "$newdir"
+    olddir="${1%/*}"
+    while [ -n "$newdir" ]; do
+        stat --printf='%a\0%U\0%G\0' -- "$olddir" | xargs -0r -n 3 sh -c 'sudo chmod "$2" -- "$1"; sudo chown "$3:$4" -- "$1";' "$newdir"
+        newdir="${newdir%/*}"
+        olddir="${olddir%/*}"
+    done
+
+    mvsafeinternal "$@"
 }
 
 dotdir="$HOME/.dotfiles"
@@ -133,7 +136,7 @@ while IFS= read -r srcfl; do
         fi
     else
         logwarn "----Source file exists but target does not, moving and linking."
-        mvsafe -- "$srcfl" "$targetfl"
+        mvsafe "$srcfl" "$targetfl"
         lnsafe -s -- "$realtargetfl" "$srcfl"
     fi
 done < "$listfl"
